version: '2.4'

services:
  yii2-web:
    image: parasgupta283/yii2-app:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - internal

networks:
  internal:
    driver: bridge
