global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['172.31.84.205:9100']
  - job_name: 'nginx'
    static_configs:
      - targets: ['172.31.84.205:9113']
