name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key
          chmod 600 private_key

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            docker pull your-dockerhub-username/yii2-app:latest
            docker service update --image parasgupta283/yii2-app:latest yii2-app-yii2-app || \
            docker service create --name yii2-app-yii2-app -p 8080:80 parasgupta283/yii2-app:latest
          EOF
