name: Deploy to EC2 via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH
        run: |
          ssh -t -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            docker pull parasgupta283/yii2-app:latest
            docker service update --image parasgupta283/yii2-app:latest yii2-web || \
            docker service create --name yii2-web -p 8080:80 parasgupta283/yii2-app:latest
          EOF
